version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: jmeter:5.6.3

jobs:
  run-jmeter-tests:
    executor: jmeter-executor
    steps:
      - checkout
      - run:
          name: Set Up JMeter
          command: |
            mkdir -p /opt/jmeter/tests
            cp -r tests/* /opt/jmeter/tests/
            # If you need to run the JMeter command, add it here
            jmeter -n -t /opt/jmeter/tests/test.jmx -l results.jtl

workflows:
  version: 2
  test:
    jobs:
      - run-jmeter-tests
