version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: circleci/openjdk:8-jdk  # Use the OpenJDK image
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout
      - run:
          name: Install JMeter 5.6.3
          command: |
            # Download JMeter 5.6.3
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
            # Extract the downloaded file
            tar -xzf apache-jmeter-5.6.3.tgz
            # Move to a more convenient location within the project directory
            mv apache-jmeter-5.6.3 ./jmeter
            # Add JMeter to PATH
            echo 'export PATH=$PATH:$(pwd)/jmeter/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install JMeter Plugins Manager
          command: |
            cd jmeter
            wget https://jmeter-plugins.org/files/plugins/JMeterPlugins-Manager.zip
            unzip JMeterPlugins-Manager.zip
            rm JMeterPlugins-Manager.zip
            # Install the required plugins
            ./bin/jmeter -n -t ./bin/jmeter-plugins-manager.jmx
      - run:
          name: Install Required Plugins
          command: |
            cd jmeter/bin
            ./jmeter-plugins-manager install jp@gc - Transactions per Second
      - run:
          name: Check JMeter Version
          command: jmeter --version
      - run:
          name: Verify JMX File
          command: |
            ls tests  # List files in the tests directory to confirm presence of the JMX file
      - run:
          name: Run JMeter Test
          command: |
            jmeter -n -t tests/test.jmx -l results.jtl  # Run tests and generate JTL
      - run:
          name: Generate HTML Report from JTL
          command: |
            jmeter -g results.jtl -o report  # Generate HTML report from JTL

      - store_artifacts:
          path: report
          destination: jmeter-report
      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - jmeter_test
