version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: cimg/openjdk:17.0  # Use OpenJDK 17 for compatibility
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout
      - run:
          name: Install JMeter 5.6.3
          command: |
            echo "Installing JMeter..."
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
            tar -xzf apache-jmeter-5.6.3.tgz
            mv apache-jmeter-5.6.3 ./jmeter
            echo 'export PATH=$PATH:$(pwd)/jmeter/bin' >> $BASH_ENV
            source $BASH_ENV
            jmeter --version  # Confirm installation
      - run:
          name: Set Heap Memory for JMeter
          command: echo 'export HEAP="-Xms2g -Xmx4g -XX:MaxMetaspaceSize=512m"' >> $BASH_ENV
      - run:
          name: Verify JMX File
          command: |
            echo "Checking JMX test file..."
            ls tests  # Ensure the JMX file exists in the 'tests' directory
      - run:
          name: Run JMeter Test in Non-GUI Mode
          command: |
            echo "Starting JMeter load test..."
            jmeter -n -t tests/VRT.jmx -l results.jtl -e -o report -Jserver.exitaftertest=true
      - run:
          name: Generate HTML Report from JTL
          command: |
            echo "Generating JMeter HTML report..."
            jmeter -g results.jtl -o report
      - store_artifacts:
          path: report
          destination: jmeter-report
      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  jmeter-workflow:
    jobs:
      - jmeter_test
