version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: cimg/openjdk:17.0  # OpenJDK 17 for compatibility
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout

      - run:
          name: Verify JMX File After Checkout
          command: |
            ls -lah tests/
            pwd

      - run:
          name: Install JMeter 5.6.3
          command: |
            wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
            tar -xzf apache-jmeter-5.6.3.tgz
            mv apache-jmeter-5.6.3 ./jmeter
            echo 'export PATH=$PATH:$(pwd)/jmeter/bin' >> $BASH_ENV
            source $BASH_ENV
            jmeter --version

      - run:
          name: Run JMeter Test in Non-GUI Mode
          command: |
            echo "Starting JMeter load test..."
            jmeter -n -t tests/PTR.jmx -l results.jtl -e -o report \
              -Jserver.exitaftertest=true \
              -Jjmeterengine.force.system.exit=true \
              -JNonGui.log_errors=true \
              -Jlog_level.jmeter=DEBUG || exit 1
            echo "JMeter Test Execution Completed."

      - run:
          name: Generate HTML Report from JTL
          command: |
            jmeter -g results.jtl -o report
            echo "Report generation completed."

      - store_artifacts:
          path: report
          destination: jmeter-report

      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  jmeter-workflow:
    jobs:
      - jmeter_test
