version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout
      - run:
          name: Install JMeter
          command: |
            sudo apt-get update
            sudo apt-get install -y jmeter python3 python3-pip
            pip3 install pandas  # Install pandas for HTML report generation
      - run:
          name: Run JMeter Test
          command: |
            jmeter -n -t tests/performance_test.jmx -l results.jtl
            jmeter -g results.jtl -o report  # Generate additional report files
      - run:
          name: Generate HTML Report from CSV
          command: |
            # Assuming the JMeter test results are in results.jtl
            # Convert results.jtl to CSV using JMeter command (if needed)
            jmeter -Jjmeter.save.format=csv -g results.jtl -o csv_report

            # Create a simple Python script to convert CSV to HTML
            echo "import pandas as pd; df = pd.read_csv('csv_report/results.csv'); df.to_html('report/report.html')" > generate_report.py

            # Run the Python script
            python3 generate_report.py

      - store_artifacts:
          path: report
          destination: jmeter-report
      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - jmeter_test
