version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: cimg/openjdk:17.0  # OpenJDK 17 for compatibility
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout  # Pull the latest code from GitHub

      # Move JMX files to the correct directory if needed
      - run:
          name: Move JMX Files to Correct Directory
          command: |
            mkdir -p tests
            mv *.jmx tests/
            ls -lah tests

      - run:
          name: Install JMeter 5.6.3
          command: |
            echo "Installing JMeter..."
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
            tar -xzf apache-jmeter-5.6.3.tgz
            mv apache-jmeter-5.6.3 ./jmeter
            echo 'export PATH=$PATH:$(pwd)/jmeter/bin' >> $BASH_ENV
            source $BASH_ENV
            jmeter --version  # Confirm installation

      - run:
          name: Set Heap Memory for JMeter
          command: |
            echo 'export JVM_ARGS="-Xms2g -Xmx4g -XX:MaxMetaspaceSize=512m"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Verify JMX File
          command: |
            echo "Checking if tests directory exists..."
            ls -lah tests || echo "ERROR: tests directory not found!"
            echo "Checking if PTR.jmx file exists..."
            if [ ! -f tests/PTR.jmx ]; then echo "ERROR: PTR.jmx not found!"; exit 1; fi
            echo "File exists, proceeding..."

      - run:
          name: Run JMeter Test in Non-GUI Mode
          working_directory: ~/project
          command: |
            echo "Starting JMeter load test..."
            jmeter -n -t tests/PTR.jmx -l results.jtl -e -o report -Jserver.exitaftertest=true || exit 1
            echo "JMeter Test Execution Completed."

      - run:
          name: Generate HTML Report from JTL
          command: |
            echo "Generating JMeter HTML report..."
            jmeter -g results.jtl -o report
            echo "Report generation completed."

      - store_artifacts:
          path: report
          destination: jmeter-report

      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  jmeter-workflow:
    jobs:
      - jmeter_test
