version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: cimg/openjdk:17.0  # OpenJDK 17 for compatibility
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout  # Pull the latest code from GitHub

      # Ensure the `tests` directory exists and contains the JMX file
      - run:
          name: Verify JMX Files After Checkout
          command: |
            echo "Checking JMX test files..."
            ls -lah
            ls -lah tests || echo "ERROR: tests directory not found!"
            if [ ! -f tests/PTR.jmx ]; then echo "ERROR: PTR.jmx not found!"; exit 1; fi
            echo "JMX file found, proceeding..."

      - run:
          name: Install JMeter 5.6.3
          command: |
            echo "Installing JMeter..."
            wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
            tar -xzf apache-jmeter-5.6.3.tgz
            mv apache-jmeter-5.6.3 ./jmeter
            echo 'export PATH=$PATH:$(pwd)/jmeter/bin' >> $BASH_ENV
            source $BASH_ENV
            jmeter --version  # Confirm installation

      - run:
          name: Set Heap Memory for JMeter
          command: |
            echo 'export JVM_ARGS="-Xms2g -Xmx4g -XX:MaxMetaspaceSize=512m"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Run JMeter Test in Non-GUI Mode
          command: |
            echo "Starting JMeter load test..."
            timeout 300 jmeter -n -t tests/PTR.jmx -l results.jtl -e -o report \
            -Jserver.exitaftertest=true \
            -Jjmeterengine.force.system.exit=true \
            -JNonGui.log_errors=true \
            -Jlog_level.jmeter=DEBUG \
            || exit 1
            echo "JMeter Test Execution Completed."




      - run:
          name: Generate HTML Report from JTL
          command: |
            echo "Generating JMeter HTML report..."
            jmeter -g results.jtl -o report
            echo "Report generation completed."

      - store_artifacts:
          path: report
          destination: jmeter-report

      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  jmeter-workflow:
    jobs:
      - jmeter_test
