version: 2.1

executors:
  jmeter-executor:
    docker:
      - image: circleci/openjdk:8-jdk  # Use a more recent JMeter Docker image
    working_directory: ~/project

jobs:
  jmeter_test:
    executor: jmeter-executor
    steps:
      - checkout
      - run:
          name: Install Python and Pip
          command: |
            sudo apt-get update
            sudo apt-get install -y jmeter python3 python3-pip
            pip3 install pandas  # Install pandas for any future use
      - run:
          name: Check JMeter Version
          command: jmeter --version
      - run:
          name: Verify JMX File
          command: |
            ls tests  # List files in the tests directory to confirm presence of the JMX file
      - run:
          name: Run JMeter Test
          command: |
            jmeter -n -t tests/test.jmx -l results.jtl  # Run tests and generate JTL
      - run:
          name: Generate HTML Report from JTL
          command: |
            jmeter -g results.jtl -o report  # Generate HTML report from JTL

      - store_artifacts:
          path: report
          destination: jmeter-report
      - store_artifacts:
          path: results.jtl
          destination: jmeter-results

workflows:
  version: 2
  test-workflow:
    jobs:
      - jmeter_test
